version: "3"

services:
  app:
    restart: always
    depends_on:
      - mongodb
    env_file:
      - ./.env
    build:
      context: "./Docker"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app/frontend
    command: bash entrypoint
    networks:
      - next-network

  mongodb:
    image: mongo:jammy
    restart: always
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    # move entrypoint scripts over with volume(?)
    # volumes:
    #   - dbdata6:/data/db
    networks:
      - next-network

volumes:
  mongodb:

networks:
  next-network:
    driver: bridge
