#!/bin/bash

npm install && # install dependencies into the docker container
# npm run dev &&   # runs the dev server
npm run start # runs the production server
npm next telemetry disable # disables nextjs telemetry